development:
  dialect: postgres
  database: bookings
  user: bookings
  password: password
  host: postgres
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://bookings:password@127.0.0.1:5432/bookings"}}