version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:11.1

  redis:
    container_name: redis
    image: redis:5.0

  api:
    container_name: api
    build:
      context: server
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ${PWD}/server:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
    depends_on:
      - redis
      - postgres

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ${PWD}/client:/usr/src/app

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3333:80'
    restart: always
    depends_on:
      - client
      - api

  worker:
    container_name: worker
    build:
      context: worker
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ${PWD}/worker:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
