version: '2.1'

services:
  express-demo:
    image: express-demo
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    labels:
      - traefik.http.routers.my-container.rule=Host(`courses`)
networks:
  default:
    external:
      name: traefik
