version: '3.4'

services:
  control:
    hostname: control
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu.bionic
    volumes:
      - ${PWD}:/root/workspace
  
  lb01:
    hostname: lb01
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu.bionic
    ports:
      - "9998:80"
      - "9999:443"

  db01:
    hostname: db01
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu.bionic

  app01:
    hostname: app01
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu.bionic

  app02:
    hostname: app02
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu.bionic
