apiVersion: v1
kind: Pod
metadata:
  name: kubia
  labels:
    app: kubia
    type: frontend
spec:
  containers:
    - name: kubia
      image: luksa/kubia
      ports:
        - name: "http"
          containerPort: 8080
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 10m
          memory: 100Mi

