version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    volumes:
      - ${PWD}/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/html:/usr/share/nginx/html
    ports:
    - "80:80"
