---
- name: Install Web Componentts
  apt:
    name:
      - apache2
      - libapache2-mod-wsgi
    state: present
  tags: ['packages']

- name: Ensure mod_wsgi enabled
  apache2_module:
    name: wsgi
    state: present
  notify: restart apache2
  tags: ['configure']

- name: deactivate default apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2
  tags: ['configure']

- name: Ensure apache2 started
  service:
    name: apache2
    state: started
    enabled: yes
