version: '3'

services:
  server:
    container_name: node-server
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.1.5
