version: "3.3"

services:

  mysql:
    image: mysql:5.7.39@sha256:0563b36ec2d1a262f79e1d8562e61f642a0f64f93306d8a709047cdea0444d0a
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: masonite
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
