apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpaca-prod
    ver: "1"
    env: prod
  name: alpaca-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpaca-prod
      ver: "1"
      env: prod
  strategy: {}
  template:
    metadata:
      labels:
        app: alpaca-prod
        ver: "1"
        env: prod
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard-amd64
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alpaca-prod
    env: prod
    ver: "1"
  name: alpaca-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: alpaca-prod
    env: prod
    ver: "1"

