apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
    ver: "2"
    env: prod
  name: kuard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuard
      ver: "2"
      env: prod
  template:
    metadata:
      labels:
        app: kuard
        ver: "2"
        env: prod
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:green
        name: kuard-amd64
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
    env: prod
    ver: "2"
  name: kuard
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
    env: prod
    ver: "2"
 
