version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/my_task.py --master -H http://master:8089 --loglevel=DEBUG -u 1 -r 1
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/my_task.py --worker --master-host master --loglevel=DEBUG -u 1 -r 1
