global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/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'
  smtp_smarthost: 'smtp.mailtrap.io:2525'
  smtp_from: 'alertmanager@prometheus.com'
  smtp_auth_username: '324318f3bdbe49854'
  smtp_auth_password: '248cbbbea53303'

route:
  # default receiver if no match found under routes:
  receiver: 'default'

  # disables aggregation entirely, passing through all alerts as-is
  group_by: ['...']
  group_wait: 40s
  group_interval: 2m
  repeat_interval: 1h
  routes:
    - receiver: 'sysadmins'
      match_re:
        app_type: (linux|windows)
      routes:
        - match:
            app_type: linux
          receiver: linux-sysadmins
          group_by: [category]
          routes:
            - match:
                severity: critical
              receiver: linux-sysadmins-critical
            - match:
                severity: warning
              receiver: linux-sysadmins-warning
        - match:
            app_type: windows
          receiver: windows-sysadmins
          routes:
            - match:
                severity: critical
              receiver: windows-sysadmins-critical
            - match:
                severity: warning
              receiver: windows-sysadmins-warning

# for simplicity, all configs use the global email and slack configs.
receivers:
  - name: 'sysadmins'
    slack_configs:
      - send_resolved: true
        title: '[sysadmins] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.example.text" . }}'
  - name: 'linux-sysadmins'
    slack_configs:
      - send_resolved: true
        title: '[linux-sysadmins] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.example.text" . }}'
  - name: 'windows-sysadmins'
    slack_configs:
      - send_resolved: true
        title: '[windows-sysadmins] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.example.text" . }}'
  - name: 'linux-sysadmins-critical'
    slack_configs:
      - send_resolved: true
        title: '[linux-sysadmins-critical] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.example.text" . }}'
  - name: 'linux-sysadmins-warning'
    slack_configs:
      - send_resolved: true
        title: '[linux-sysadmins-warning] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.example.text" . }}'
  - name: 'windows-sysadmins-critical'
    slack_configs:
      - send_resolved: true
        title: '[windows-sysadmins-critical] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.example.text" . }}'
  - name: 'windows-sysadmins-warning'
    slack_configs:
      - send_resolved: true
        title: '[windows-sysadmins-warning] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.example.text" . }}'

  - name: 'default'
    email_configs:
      - to: 'enesanbar@gmail.com'
        send_resolved: true
    slack_configs:
      - send_resolved: true
        title: '[default] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.example.text" . }}'
        actions:
          - type: button
            text: Runbook
            url: '{{ .CommonAnnotations.runbook_url }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
