apiVersion: apps/v1
kind: Deployment
metadata:
  name: tolerations-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tolerations-1
  template:
    metadata:
      labels:
        app: tolerations-1
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
