groups:
  - name: Instance
    rules:
      # Alert for any instance that is unreachable for > 1 minutes
      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          team: dota
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute"
          runbook_url: "https://example.com"
