groups:
  - name: app rules
    rules:
    - record: job:app_request_latency_seconds:rate1m
      expr: rate(http_response_latency_seconds_sum[1m]) / rate(http_response_latency_seconds_count[1m])

    - alert: AppLatencyAbove2sec
      expr: 2 < job:app_request_latency_seconds:rate1m < 5
      for: 2m
      labels:
        severity: warning
        app_type: python
      annotations:
        summary: 'app latency is going high'
        description: 'App latency of instance {{ $labels.instance }} of job {{ $labels.job }} is {{ $value }} for more than 5 minutes.'
        app_link: 'http://localhost:8000/'

    - alert: AppLatencyAbove5sec
      expr: job:app_request_latency_seconds:rate1m >= 5
      for: 2m
      labels:
        severity: critical
        app_type: python
      annotations:
        summary: 'app latency is over 5 seconds.'
        description: 'App latency of instance {{ $labels.instance }} of job {{ $labels.job }} is {{ $value }} for more than 5 minutes.'
        app_link: 'http://localhost:8000/'
