// Code generated by mockery 2.9.2. DO NOT EDIT.

package mocks

import (
	models "github.com/enesanbar/workspace/golang/projects/vigilate/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// PrefRepository is an autogenerated mock type for the PrefRepository type
type PrefRepository struct {
	mock.Mock
}

// AllPreferences provides a mock function with given fields:
func (_m *PrefRepository) AllPreferences() ([]models.Preference, error) {
	ret := _m.Called()

	var r0 []models.Preference
	if rf, ok := ret.Get(0).(func() []models.Preference); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Preference)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
