version: '3.0'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
    - "3001:3001"

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
    - "3000:80"
  
  rtmpserver:
    build:
      context: rtmpserver
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
